### ISSUE TITLE
Installation instruction unclear

### ISSUE THREAD

**Issue by MathijsNL** [ros-industrial/ur_modern_driver#134]
Hi there,

> Installation
> 
> Just clone the repository into your catkin working directory and make it with catkin_make.

Should be changed to:

> Installation
> 
> Just clone the repository into your catkin/src directory and make it with catkin_make.

Because right now it gives the impression that it should be in the catckin_ws root.

**Comment by gavanderhoorn** [comment]
Thanks for reporting this.

I believe we assume a certain level of familiarity with ROS & Catkin concepts, but we can probably add something like "clone is into the source space of your Catkin workspace".

**Comment by ipa-nhg** [comment]
Fixed: https://github.com/ros-industrial/ur_modern_driver/pull/319

**Comment by gavanderhoorn** [comment]
Fixed in #319.
