### ISSUE TITLE
Driver crashes when receiving a trajectory with only one point and time_from_start set to 0

### ISSUE THREAD

**Issue by ThomasTimm** [ros-industrial/ur_modern_driver#14]
Implement a check that verifies that the last point has a time_from_start larger than zero

**Comment by harshmdeshpande** [comment]
Is this problem solved? I had the same issue last week.

**Comment by gavanderhoorn** [comment]
I'm closing this as we've officially deprecated this package.

Refer to the [announcement on ROS Discourse](https://discourse.ros.org/t/deprecation-of-ur-modern-driver/11629).
