### ISSUE TITLE
Missing controller package dependencies

### ISSUE THREAD

**Issue by mrjogo** [ros-industrial/ur_modern_driver#145]
Commit https://github.com/ThomasTimm/ur_modern_driver/commit/9a94eb50b11f2595ca223467aa993862d92134bd removed the ros_controllers dependency from package.xml because it's a metapackage, but did not add in the individual controller packages that are still dependencies, such as force_torque_sensor_controller.

**Comment by miguelprada** [comment]
My bad. :sweat_smile: 

Can you create a PR adding run dependencies on the controllers required by the provided controller configurations?

**Comment by gavanderhoorn** [comment]
Fixed in a2137b47 (part of https://github.com/Zagitta/ur_modern_driver/pull/16) which is now `kinetic-devel`.
