### ISSUE TITLE
get_inverse_kinem

### ISSUE THREAD

**Issue by mercury070599** [ros-industrial/ur_modern_driver#182]
Hi,
My data format is in the form of a pose that describes the coordinates and orientation of TCP in the robot's base frame. On reading the driver code, it seems that joint positions are only published. In order to obtain the joint angles in the joint space,I sent the get_inverse_kin command through the URScript topic. I would like to know how can I ensure that these joint angles are used for the interpolation that the ur_modern_driver implements as it seems there is no function for the client socket on the ur robot to send data to ros.

Regards

**Comment by gavanderhoorn** [comment]
> On reading the driver code, it seems that joint positions are only published

On the `/joint_states` topic, that is correct, but the driver also publishes a TF frame called `tool0_controller` that corresponds directly to the Cartesian TCP pose the UR controller uses. The transform `base->tool0_controller` corresponds to the `base->tcp` transform as used by the controller.

> In order to obtain the joint angles in the joint space,I sent the get_inverse_kin command through the URScript topic. I would like to know how can I ensure that these joint angles are used for the interpolation that the ur_modern_driver implements as it seems there is no function for the client socket on the ur robot to send data to ros.

I'm sorry, but I don't understand what you are asking here.

The `/joint_states` topic already receives messages with the joint angles, so I don't understand why you are using `get_inverse_kin` again there.

> it seems there is no function for the client socket on the ur robot to send data to ros.

That is correct: you cannot receive any return values that may be emitted by URScript functions, the URScript topic is one-way.

**Comment by gavanderhoorn** [comment]
I'm closing this as I believe you're questions have been addressed/answered.

If that is not the case, please keep commenting on the issue.
