### ISSUE TITLE
Speedj missing parameters

### ISSUE THREAD

**Issue by Ashen1994** [ros-industrial/ur_modern_driver#187]
![default](https://user-images.githubusercontent.com/35393499/43628182-cde0603a-972b-11e8-8941-dada0bd2ed3f.jpg)

Display type error when using ur_modern_drive, Speedj missing parameters. The speedj on the needs exactly the same three parameters but given two dispalyed on the  teach pendant.

**Comment by gavanderhoorn** [comment]
There is quite a history with UR, `speedj(..)`, how many arguments it really needs and those nrs (*and* the interpretation / semantics of the arguments) changing over time.

See #92 (and the linked issues there, such as #100) for some previous discussion.

If this has changed again, the driver will have to be updated.

But without more information (ie: your controller, version of polyscope, how you are using the driver, etc), we can't really say anything.

**Comment by Ashen1994** [comment]
Thank you ,you are right.I have solved this problem by upgrated the version of polyscope. 
void UrRealtimeCommunication::setSpeed(double q0, double q1, double q2,
		double q3, double q4, double q5, double acc) {
	char cmd[1024];
	if( robot_state_->getVersion() >= 3.3 ) {
		sprintf(cmd,
				"speedj([%1.5f, %1.5f, %1.5f, %1.5f, %1.5f, %1.5f], %f, 0.008)\n",
				q0, q1, q2, q3, q4, q5, acc);
	}
	else if( robot_state_->getVersion() >= 3.1 ) {
		sprintf(cmd,
				"speedj([%1.5f, %1.5f, %1.5f, %1.5f, %1.5f, %1.5f], %f)\n",
				q0, q1, q2, q3, q4, q5, acc);
	}
	else {
		sprintf(cmd,
				"speedj([%1.5f, %1.5f, %1.5f, %1.5f, %1.5f, %1.5f], %f, 0.02)\n",
				q0, q1, q2, q3, q4, q5, acc);		
	}

**Comment by gavanderhoorn** [comment]
I'm not sure what you did actually.

Could you give a bit more details?

**Comment by Ashen1994** [comment]
Before I modified，the version of my polyscope is 3.1. The speedj has one more parameter when the version is greater than 3.3. I'm not sure, but I upgrate the version of polyscope to 3.3.  Everything is well.

**Comment by gavanderhoorn** [comment]
It would be great if this could be submitted as a PR against `kinetic-devel`.

**Comment by gavanderhoorn** [comment]
I'm closing this as we've officially deprecated this package.

Refer to the [announcement on ROS Discourse](https://discourse.ros.org/t/deprecation-of-ur-modern-driver/11629).

**Comment by gavanderhoorn** [comment]
Please use `ur_robot_driver` with CB3 and e-series controllers.
