### ISSUE TITLE
 joint limits restricted to [-pi,pi]

### ISSUE THREAD

**Issue by weiwuhuhu** [ros-industrial/ur_modern_driver#192]
when i excute the  command

```
roslaunch ur_bringup ur5_bringup.launch limited:=true robot_ip:=IP_OF_THE_ROBOT [reverse_port:=REVERSE_PORT]
```

The plan in moveit always failed.How can I resolve this problem.

**Comment by gavanderhoorn** [comment]
I'm going to close this due to inactivity.

If you get around to it, please update the issue with more information and potentially re-open.
