### ISSUE TITLE
How to read the input IO signal of the ur5 robot

### ISSUE THREAD

**Issue by ChenLong-Cristian** [ros-industrial/ur_modern_driver#200]
IS there anybody can tell me how to read the input IO signal of the ur5 robot control box. 
Thanks a lot!

**Comment by gonzalocasas** [comment]
Did you try the `/ur_driver/io_states` topic?

**Comment by gavanderhoorn** [comment]
I believe @gonzalocasas answered your question @ChenLong-Cristian.

As such I'm going to close this. Please feel free to keep commenting though.
