### ISSUE TITLE
How to control the controller IO output？

### ISSUE THREAD

**Issue by Tetexu** [ros-industrial/ur_modern_driver#202]
I am using the UR3 now and now I need to control the release and clamping of the jaws. Can anyone tell me how to control the IO port of the controller? Thank you very much!

**Comment by gavanderhoorn** [comment]
It depends a bit on which IOs you're looking to control, but the `/ur_driver/set_io` service allows you to control at least the standard digital and analogue IO on the controller.

**Comment by gavanderhoorn** [comment]
I believe this is not an issue with the package in this repository so I'll close it.

Please feel free to keep commenting on it.

**Comment by Tetexu** [comment]
Thank you
