### ISSUE TITLE
Using /joint_speed

### ISSUE THREAD

**Issue by BigHopes** [ros-industrial/ur_modern_driver#223]
Hello all,

I am trying to do a speed control in a UR5 robot and using python.
Please would you give me an example of publishing a message, I think it is something like the following, but how to complete and how to provide it with the header?

`pub=rospy.Publisher('/joint_speed', trajectory_msgs.msg.JointTrajectory,queue_size=30)`
`pub.publish("??)")` 

Regards,

**Comment by gavanderhoorn** [comment]
In principle with the `joint_speed` topic you need to publish a `JointTrajectory` with a single `JointTrajectoryPoint` in it. Populate the `velocities` field with the desired velocities.

The [jog_arm](https://github.com/UTNuclearRoboticsPublic/jog_arm) package does this. You could take a look at it.

**Comment by gavanderhoorn** [comment]
The recently added support for `JointGroupVelocityControllers` might be a nicer way to do this though.

**Comment by gavanderhoorn** [comment]
As this is not really an issue with the code in this package I'm going to close the issue.

Feel free to keep commenting on it though.
