### ISSUE TITLE
limit to amount of targets

### ISSUE THREAD

**Issue by Chriszlf** [ros-industrial/ur_modern_driver#272]
I'm now trying to send 5000 targets to a Bartlett UR10 robot via ROS. But the robot gives no reaction at all. It looks like there is a limit to the amount of targets. Could anyone give some suggestion on such a case?

**Comment by gavanderhoorn** [comment]
@Chriszlf: I've moved your issue to `ur_modern_driver` as I believe you're using that (`ur_driver` doesn't have a `URScript` topic).
