### ISSUE TITLE
RobotStatus publisher does not set timestamp

### ISSUE THREAD

**Issue by gavanderhoorn** [ros-industrial/ur_modern_driver#286]
Noticed in the output shown in #285: the `RobotStatus` publisher in `mb_publisher.cpp` does not set the timestamp of the messages it publishes:

https://github.com/ros-industrial/ur_modern_driver/blob/195f5e937af6459f8808df3f021923614e761413/src/ros/mb_publisher.cpp#L39-L94

That's not very nice and should be fixed.

**Comment by miguelprada** [comment]
Fixed in #287.
