### ISSUE TITLE
UR Driver gives my wrong poses

### ISSUE THREAD

**Issue by chandanlal92** [ros-industrial/ur_modern_driver#292]
Hello,

I am using UR_modern driver with UR-10 Robot to do hand_eye calibration using easy_handeye calibration ros service. The poses which I am recieving from the ur driver seems to be mismatched with the direction.
It gives me
x=-363.23 where my robot panel shows X=363.23
Same cases with Y.Z seems to be correct.

**Comment by chandanlal92** [comment]
How to test the current poses?

**Comment by gavanderhoorn** [comment]
You'll have to tell us which transform you are looking at.

If you're inspecting `base_link->tool0`, the 180 degree difference is expected.

If you're using `base->tool0`, then you should get the proper poses.

All depending on your toolframe setup also of course.

**Comment by chandanlal92** [comment]
Both base->tool0 and base_link->tool0

**Comment by chandanlal92** [comment]
Now I am getting correct value after using base->tool0. Thank you for the info.

**Comment by gavanderhoorn** [comment]
Please also note: this is not something in `ur_modern_driver`, but in `ur_description` ([here](https://github.com/ros-industrial/universal_robot/blob/2665f4bed158a8962e7ed72c7a83835cb872b59b/ur_description/urdf/ur5.urdf.xacro#L326-L330
)).
