### ISSUE TITLE
Can this driver connect the arms of the ur e-series?

### ISSUE THREAD

**Issue by wzy19950426** [ros-industrial/ur_modern_driver#297]
I want to use this driver to connect ur5-e,I have replaced the urdf description file in "ur5_bringup.launch".But it doesn't work.I can't get the current pose information of the arm.

**Comment by gavanderhoorn** [comment]
Please refer to #216.

**Comment by gavanderhoorn** [comment]
As #216 was specifically created for this I'm going to close this issue.

Please continue any discussion on the PR.
