### ISSUE TITLE
how to stop the ur5e when it is encountered with a huamn body

### ISSUE THREAD

**Issue by Jason-Zhou1** [ros-industrial/ur_modern_driver#298]
Hi all,

I am running a ur5e robot arm in Kinetic on Ubuntu 16.04. I want the arm to stop if it is encountered with a human body. For example, when a human is pushing the moving arm stop it. I believe it is a function of safety as a cobot, but I don't know how to set this function. May anyone be able to help me out? 

Thank you!

**Comment by gavanderhoorn** [comment]
This doesn't sound like a question to submit to the issue tracker of a ROS driver. More something to ask an integrator or an industrial robotics forum.

If you're specifically wondering how to do this with ROS, then my answer (right now) would be: don't. Especially not if it needs to be safety-rated.

ROS 1 was not made for this type of applications.

> I believe it is a function of safety as a cobot,

exactly, so use the functionality provided by the controller for this.

> but I don't know how to set this function

then I would suggest looking at/in the manuals that document those features, ask your distributor/vendor or an integrator.

**Comment by gavanderhoorn** [comment]
As this is not something actionable (in the context of the package hosted in this repository) I'm going to close the issue.

Feel free to keep commenting on it of course.
