### ISSUE TITLE
Is it possible to reset a protective stop using the driver?

### ISSUE THREAD

**Issue by SimonBirrell** [ros-industrial/ur_modern_driver#306]
Our UR10 does a protective stop from time to time (probably because of a heavy payload). When this happens we typically unlock the arm from the Teach Pendant and move it to a more comfortable position before resuming.

Is this reset something we could do from the driver?

**Comment by miguelprada** [comment]
I don't think you can do it through this driver, although it should be relatively straightforward to implement that functionality yourself in a separate node that connects to the _Dashboard Server_ ([CB-Series](https://www.universal-robots.com/how-tos-and-faqs/how-to/ur-how-tos/dashboard-server-cb-series-port-29999-15690/) and [e-Series](https://www.universal-robots.com/how-tos-and-faqs/how-to/ur-how-tos/dashboard-server-e-series-port-29999-42728/)).

I've used that interface sometimes for convenience (even to power on/off the servos and release the brakes), but keep in mind that it may not be the best idea to do so from the safety perspective.
