### ISSUE TITLE
/joint_speed

### ISSUE THREAD

**Issue by Tina1994** [ros-industrial/ur_modern_driver#309]
/joint_speed : Takes messages of type trajectory_msgs/JointTrajectory. Parses the first JointTrajectoryPoint and sends the specified joint speeds and accelerations to the robot. This interface is intended for doing visual servoing and other kind of control that requires speed control rather than position control of the robot. Remember to set values for all 6 joints. Ignores the field joint_names, so set the values in the correct order.
Hello, I can not find /joint_speed topic in my rostopic list .  I opened all the codes in your repo, I can not find which node subscribe the topic /joint_speed. That is mean is there missing the topic /joint_speed ?

**Comment by gavanderhoorn** [comment]
If you're running `kinetic-devel`, there is no `joint_speed` topic any more.

Refer to #218.
