### ISSUE TITLE
UR script messages

### ISSUE THREAD

**Issue by JRosaa** [ros-industrial/ur_modern_driver#329]
Hello. 
I am using an adaptation of this driver for UR5e arm. 
I understand the topic /ur_driver/URScript receives commands according to The URScript Programming Language. However, most of these commands have a return value, which I cannot access. Is there a way to read this command return value?

**Comment by gavanderhoorn** [comment]
The urscript topic is not a replacement for running actualy urscript scripts on the controller, but a ROS-i-fied way to submit scriplets to port `30002`. It's completely analogous to how you would do this without ROS (ie: open a connection to `tcp://:30002` and `write(..)` some ascii text to the `fd`).

It also comes with the exact same restrictions (such as not returning your the return values).

This does not seem to be something we can do anything about.
