### ISSUE TITLE
How to control the IO states of  UR

### ISSUE THREAD

**Issue by GoogleMike** [ros-industrial/ur_modern_driver#338]
Since the driver can control the io states, then how to control it by code?
I'm not familiar with the ros and ur. Could you please give me some suggestions?

**Comment by gavanderhoorn** [comment]
> then how to control it by code?

if "by code" you mean from a ROS node: write a [service client](http://wiki.ros.org/ROS/Tutorials/WritingServiceClient%28python%29) (rospy tutorial) for the [SetIO](http://docs.ros.org/kinetic/api/ur_msgs/html/srv/SetIO.html) service. Be sure to specify the correct values for `fun`, `pin` and `state`.

**Comment by gavanderhoorn** [comment]
Closing as this is not an issue with the package in this repository.
