### ISSUE TITLE
"FreeDriver" of UR5

### ISSUE THREAD

**Issue by ghx-0228** [ros-industrial/ur_modern_driver#340]
Can I use this driver to extract the "freedrive" signal (off/on) from real UR5?

**Comment by gavanderhoorn** [comment]
I can't verify whether we're publishing it already, but the RT state data contains a field `robotMode` that encodes what mode the robot is in. `BACKDRIVE` or `FREEDRIVE` would indicate whether the freedrive button is being pressed (or actually: whether the robot is actually in that mode. It may refuse to enter freedrive mode).

**Comment by gavanderhoorn** [comment]
Closing as it's not an issue with the package in this repository (right now).

If you can't make this work, please log as an enhancement -- and submit a PR if you'd like this supported. Otherwise it may take a while before this is implemented.
