### ISSUE TITLE
in ros_control mode, ur_script cannot be used normally.

### ISSUE THREAD

**Issue by zhengxiang94** [ros-industrial/ur_modern_driver#358]
I want to control gripper(onrobot rg2) by ur_script. When I use ur5_bring_up.launch, this method can be used normally. However, When I use ur5_ros_control.launch, it does not work.

**Comment by gavanderhoorn** [comment]
I'm closing this as we've officially deprecated this package.

Refer to the [announcement on ROS Discourse](https://discourse.ros.org/t/deprecation-of-ur-modern-driver/11629).
