### ISSUE TITLE
Suggestion: change default branch

### ISSUE THREAD

**Issue by atyshka** [ros-industrial/ur_modern_driver#359]
Is there a good reason why the default branch is the deprecated master? Just a suggestion that might make things easier for users. Spent a good 15 minutes debugging my deps in my submodules before I saw the Readme and switched the branch. If there's some reason it needs to be default for backwards-compatibility that's alright, but making this change would be great for ease of use.

**Comment by gavanderhoorn** [comment]
Please see #245 for what needs to be done before we can do this.
