### ISSUE TITLE
Digital Output while Movement

### ISSUE THREAD

**Issue by Zampaloni** [ros-industrial/ur_modern_driver#368]
Hey, 
is there any way to control the digital output while the robot is in a movement. 
You would help me a lot. 
Thanks in advance.

**Comment by gavanderhoorn** [comment]
You should be able to use the `SetIO` service during a motion.

The service wraps a `sec` program which should not interfere with a motion being executed.

**Comment by gavanderhoorn** [comment]
As this is not an issue with the package in this repository, I'm going to close the issue.

Please also be aware of the fact that this package has been deprecated.

See #367 and the discourse post linked in that.
