### ISSUE TITLE
kinematics_config argument is needed?

### ISSUE THREAD

**Issue by AhmetMericOzcan** [ros-industrial/ur_modern_driver#369]
Trying to use it on real robot with Moveit, and I am trying to use it with limited version since otherwise it can create unwanted dangerous situations.

However even though I can connect to robot with certain IP, when run the command suggested I got this error

`roslaunch ur_robot_driver ur5_bringup.launch robot_ip:=10.0.0.2 limited:=true
`
```
unused args [kinematics_config] for include of [/home/meric/c_ws/src/universal_robot/ur_description/launch/ur5_upload.launch]
The traceback for the exception was written to the log file
```

Any Ideas?

**Comment by hariharan382** [comment]
please say how you solved it
