### ISSUE TITLE
Migrate RobotHW to combiner_robot_hw

### ISSUE THREAD

**Issue by paulbovbel** [ros-industrial/ur_modern_driver#70]
Thanks for developing this fantastic driver.

I'm working on moving the Clearpath Husky to a combined_robot_hw implementation for kinetic. This has the advantage of using only one controller_manager per hardware robot, with multiple HW endpoints (base and arm) as well as controllers loaded in-process.

Would you consider adapting your driver to do the same? It's kind of lacking documentation, but exciting nonetheless (see video here https://github.com/ros-controls/ros_control/issues/237)

**Comment by gavanderhoorn** [comment]
Has the "kind of lacking documentation" situation been improved?

**Comment by gavanderhoorn** [comment]
I'm closing this as we've officially deprecated this package.

Refer to the [announcement on ROS Discourse](https://discourse.ros.org/t/deprecation-of-ur-modern-driver/11629).

**Comment by gavanderhoorn** [comment]
Note that initial support for `CombinedRobotHW` was merged in `ur_robot_driver` in https://github.com/UniversalRobots/Universal_Robots_ROS_Driver/pull/34.
