### ISSUE TITLE
It seems like the realtime interface may be more stable than the reverse-connection

### ISSUE THREAD

**Issue by davebenson** [ros-industrial/ur_modern_driver#71]
I'm not exactly sure I understand what's going on..., so please comment...

We were having issues where the UR touchscreen would popup a dialog, saying that the UR-script program (uploaded from ur-modern-driver) had taken more than its time-slice.

So, we tried various things, and a simply low-level program worked, so we tried controlling just via servoj() commands written to the realtime interface...

Maybe this should be a mode of operation on modern UR firmware, instead of the "reverse connection"?

**Comment by gavanderhoorn** [comment]
I'm closing this as we've officially deprecated this package.

Refer to the [announcement on ROS Discourse](https://discourse.ros.org/t/deprecation-of-ur-modern-driver/11629).

**Comment by gavanderhoorn** [comment]
`ur_robot_driver` has moved to RTDE for interacting with the controller. The assumption is that this will prove more stable than the primary, secondary or matlab/real-time interfaces.
