### ISSUE TITLE
Can we really omit time argument in speedj?

### ISSUE THREAD

**Issue by sergeant-wizard** [ros-industrial/ur_modern_driver#92]
Regarding [this call](https://github.com/ThomasTimm/ur_modern_driver/blob/master/src/ur_realtime_communication.cpp#L103)
to `speedj`, I was having an issue where the published `/joint_states/velocity` was oscillating like this:

![without_time](https://cloud.githubusercontent.com/assets/6078052/22003635/6b989734-dc98-11e6-9974-6d624eddb286.png)

Where I was publishing to `/ur_modern_driver/joint_speed` at 125Hz.
When I added the `time` argument in `speedj` as `0.008` in the above line, I got a smooth output:

![with_time](https://cloud.githubusercontent.com/assets/6078052/22003673/a92479d8-dc98-11e6-844e-9df1b2cd5fcf.png)

I noticed that @ThomasTimm mentioned in #55 that the time argument doesn't really matter, but just wanted you to know that I needed to specify the argument to get stable results.

The UR software version is 3.3.1.237, and I'm using UR5.
ROS distro is Indigo on Ubuntu 14.04.

**Comment by mitch1044444** [comment]
@sergeant-wizard Hey, I wonder if you could share how to plot this? I couldn't find much information on how to use URscript in ROS, and I'm afraid I might break our robot here, any help would be deeply appreciated.

**Comment by sergeant-wizard** [comment]
@mitch1044444 
I published the joint velocities to `ur_driver/joint_speed` as `JointTrajectoryPoint`s, subscribed to '/joint_states' and recorded the latest of each at every control frame.
Don't worry, your robot will not break if you start with very small velocities.

**Comment by sergeant-wizard** [comment]
https://gist.github.com/sergeant-wizard/bd9d305d4f02e0caa424cde4af0537ce

something like this, though it hasn't been tested

**Comment by gavanderhoorn** [comment]
Related to #55 and #62.

**Comment by inksci** [comment]
You have mentioned that:
"I published the joint velocities to ur_driver/joint_speed as JointTrajectoryPoints"

Therefore, could you tell me that if I use the speedj for /ur_driver/URScript, rather than use ur_driver/joint_speed, will the results be same?

**Comment by gavanderhoorn** [comment]
I'm closing this as we've officially deprecated this package.

Refer to the [announcement on ROS Discourse](https://discourse.ros.org/t/deprecation-of-ur-modern-driver/11629).

**Comment by gavanderhoorn** [comment]
This should no longer be an issue as `ur_robot_driver` uses a somewhat different approach to controlling the robot.

If this *is* still an issue, please report it over at the `ur_robot_driver` issue tracker.
